### PR TITLE
SSL Project Support

### PR DESCRIPTION
**Pull request by bunnymatic**
- adding support for ssl communication with pivotal tracker via --use-ssl commandline opts or git config options

Hey there

I know there was an issue in the github issue tracker for this.  And i just ran into it on one of my projects.  I've implemented a fix that uses a config (commandline or git config) option to use-ssl.  I updated specs accordingly.

Cheers
Jon Rogers @ 2rye.com

### CODE REVIEW

**Comment by trydionel** [comment]
Thanks bunnymatic! Would you mind to revert your changes to VERSION, the gemspec and spec_helper.rb? I'd be happy to merge this in after that.

**Comment by anderssonjohan** [comment]
Oh, it would be great to have support for SSL. Great work!
We're on SSL only and when trying git-pivotal all I got was this:

Retrieving latest chores from Pivotal Tracker for Johan Andersson...
/opt/local/lib/ruby/gems/1.8/gems/rest-client-1.6.3/lib/restclient/abstract_response.rb:48:in `return!': 400 Bad Request (RestClient::BadRequest)
    from /opt/local/lib/ruby/gems/1.8/gems/rest-client-1.6.3/lib/restclient/request.rb:228:in`process_result'
    from /opt/local/lib/ruby/gems/1.8/gems/rest-client-1.6.3/lib/restclient/request.rb:176:in `transmit'
    from /opt/local/lib/ruby/1.8/net/http.rb:543:in`start'
    from /opt/local/lib/ruby/gems/1.8/gems/rest-client-1.6.3/lib/restclient/request.rb:170:in `transmit'
    from /opt/local/lib/ruby/gems/1.8/gems/rest-client-1.6.3/lib/restclient/request.rb:64:in`execute'
    from /opt/local/lib/ruby/gems/1.8/gems/rest-client-1.6.3/lib/restclient/request.rb:33:in `execute'
    from /opt/local/lib/ruby/gems/1.8/gems/rest-client-1.6.3/lib/restclient/resource.rb:54:in`get'
    from /opt/local/lib/ruby/gems/1.8/gems/pivotal-tracker-0.3.1/lib/pivotal-tracker/project.rb:14:in `find'
    from /opt/local/lib/ruby/gems/1.8/gems/git-pivotal-0.8.0/bin/../lib/commands/base.rb:51:in`project'
    from /opt/local/lib/ruby/gems/1.8/gems/git-pivotal-0.8.0/bin/../lib/commands/pick.rb:71:in `story'
    from /opt/local/lib/ruby/gems/1.8/gems/git-pivotal-0.8.0/bin/../lib/commands/pick.rb:28:in`run!'
    from /opt/local/lib/ruby/gems/1.8/gems/git-pivotal-0.8.0/bin/git-chore:7
    from /opt/local/bin/git-chore:19:in `load'
    from /opt/local/bin/git-chore:19

Everything worked well when turning off SSL for the project.

Keep it up...

**Comment by bunnymatic** [comment]
@anderssonjohan, this fix will get around the exact bug you have showing.

@trydionel, sorry about the version mod.  i meant to leave that out of the checkin.  I'll get that fixed up and resubmitted.

cheers

**Comment by bunnymatic** [comment]
i removed the version mods and re-pushed.  Do I need to submit another pull request?  or can you pull the 2 commits together?

**Comment by trydionel** [comment]
Nope, that'll do the trick! (Isn't Github's new pull interface amazing?) I'll review and merge it this weekend.

Thanks bunnymatic!

**Comment by anderssonjohan** [comment]
@trydionel: Just wondering if you have an ETA for your merge? Big thanks in advance!

**Comment by trydionel** [comment]
Sorry folks, I was tied up with work this weekend. I'll do my best to get this out in the next couple days.

**Comment by anderssonjohan** [comment]
Awesome.
Den 8 aug 2011 21.52 skrev "trydionel" <
reply@reply.github.com>:

**Comment by trydionel** [comment]
Merged and released! Grab v0.8.1 for SSL support. Thanks bunnymatic!

**Comment by bunnymatic** [comment]
glad i could help.

thanks for the merge.
jon

**Pull request closed without merging**
