### PR TITLE
Add a git function to get information about the branch

### PR DESCRIPTION
**Pull request by addynaik**
If you are working on multiple branches there is no way to determine the information on the branch from the branch name.. since its sort of encrypted "feature-482992". this will add "git pivotinfo" which will give information about the branch

### CODE REVIEW

**Comment by trydionel** [comment]
You've been busy on this codebase! Sorry for all the delay on my part -- we've been pushing towards a big release at the office, and it's consumed my life recently :) I haven't had time to go through the branch in detail, but do have a couple of cursory questions:
- Do you have any ideas on testing it, either with Cucumber or RSpec?
- It's a bit of bikeshedding, but `git pivotinfo` feels awkward to me. `git info` isn't a git builtin, so maybe we could go that route? I'm contemplating namespacing all of these commands under `git pivotal` in the future to prevent collisions with other extensions (e.g., `git pivotal feature`), so `info` would line up with that nicely. Thoughts?

Thanks for all the work you've put in Addy!

**Comment by addynaik** [comment]
I think the only reason it was pivotinfo was to namespace it just in case. but ifyou were planning to move to "git pivotal" neways then we can probably do info. 

let me think about the rspecs and get back.

**Comment by munshkr** [comment]
I also thought it's a good idea to use a namespace like 'pivotal', so I made some changes in my fork. Tell me if it's ok with you and I'll send you a pull request.

**Comment by trydionel** [comment]
Thanks for that munshkr! I'll take a look this weekend.

**Comment by trydionel** [comment]
Hey Addy! I've just merged your code into my development branch. I renamed Pivotinfo to Info as we discussed, and threw in a quick Cucumber suite to test out the main bits. Thanks again!

Munshkr, I'm closing this ticket, but I'd like to keep chatting about namespacing the commands. Please join in the conversation!

**Pull request merged**
